import { Metadata } from "next";
import { ReactQueryProvider } from "./ReactQueryProvider";
import Footer from "@/widgets/Footer/UI/Footer";

import "./styles/globals.scss";

export const metadata: Metadata = {
  title: "Online Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="root-layout">
          <ReactQueryProvider>
            <main className="content">{children}</main>
          </ReactQueryProvider>
          <Footer />
        </div>
      </body>
    </html>
  );
}
