import { Metadata } from "next";
import { ReactQueryProvider } from "./ReactQueryProvider";
import Navbar from "@/widgets/Navbar/UI/Navbar";
import Footer from "@/widgets/Footer/UI/Footer";

import "./styles/globals.scss";

export const metadata: Metadata = {
  title: "Online Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>
          <main>{children}</main>
          <Footer />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
