import { Metadata } from "next";
import { ReactQueryProvider } from "./ReactQueryProvider";
import Footer from "@/widgets/Footer/UI/Footer";
import ThemeProviders from "./ThemeProviders";

import "./styles/globals.scss";
import "./styles/themes.scss";

export const metadata: Metadata = {
  title: "Online Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className="root" lang="en">
      <body className="root">
        <div className="root-layout">
          <ReactQueryProvider>
            <ThemeProviders>
              <main className="content">{children}</main>
            </ThemeProviders>
          </ReactQueryProvider>
        </div>
        <Footer />
      </body>
    </html>
  );
}
